Repository RedHatInsights/insights-results-aggregator, pull requests merged in 2020-03, with the labels that each got.

#207 Added docker-compose config for better local development experience
  README.md
Labels: documentation

#228 [stable] First stable release
  Dockerfile
  Jenkinsfile-smoke.groovy
  Makefile
  README.md
  configuration_test.go
  consumer/consumer.go
  consumer/consumer_test.go
  goerrcheck.sh
  local_storage/Dockerfile.postgres
  local_storage/create_database_docker.sh
  local_storage/dockerize_postgres.sh
  metrics/metrics_test.go
  migration/migration.go
  server/server_test.go
  storage/storage.go
  storage/storage_test.go
Labels: stable

#247 Add second migration for content tables
  migration/migration.go
  migration/migration2.go
Labels: question
